OI-273: Fix Idea installation.
istolar/openideal pull request #45
Opened 2021-01-12 14:45 UTC by nvelychenko

2021-01-14 11:01 UTC, db-Matroskeen requested changes
@nvelychenko, can we move the cache rebuild into a separate file? So it'll be similar to `rebuild.php`.

2021-01-14 11:01 UTC, db-Matroskeen commented on idea.install
> +function _rebuild_cache() {
Can we name it `_idea_rebuild_cache()` ?

2021-01-14 11:01 UTC, db-Matroskeen commented on idea.install
> + * We should rebuild Drupal cache because rules module after the
As for me, the description can be simplified, something like:

_Rules require clearing the cache to rebuild the container and register new rules events.
Clearing cache in hook_install() didn't help, that's why it was moved to shutdown function._

Feel free to rephrase it a little, the idea is just to make it short and clear.

2021-01-14 11:01 UTC, db-Matroskeen commented on idea.install
> +  if (file_exists(DRUPAL_ROOT . '/autoload.php')
Do we really need to check if those files exist? If they don't, then we're kind of in trouble anyway.

I think conditions can be removed, please take a look into `rebuild.php`.

2021-01-15 17:33 UTC, nvelychenko commented on idea.install
> +function _rebuild_cache() {
Done.

2021-01-15 17:33 UTC, nvelychenko commented on idea.install
> +  if (file_exists(DRUPAL_ROOT . '/autoload.php')
Removed condition.

2021-01-15 17:34 UTC, nvelychenko commented
> @nvelychenko, can we move the cache rebuild into a separate file? So it'll be similar to `rebuild.php`.

I think it doesn't make sense. We have a small function that's we need.

2021-01-18 08:19 UTC, db-Matroskeen commented
Looks good, thanks!

2021-01-18 08:19 UTC, merged