OI-159 Implement: "user_mention" Message template, Rules action - "Cr…
istolar/openideal pull request #8
Opened 2020-09-29 15:06 UTC by nvelychenko

…eate message after mentioning user". Add appropriate message_template texts for the message displayed itslef, email subject and body. Add additional conditions for "activity feed" views. Rework the MessageAction.

2020-09-30 09:33 UTC, db-Matroskeen commented
I'm just curious to know how it'll work in the following cases:
1) Mention user in the existing comment (via "Edit" action);
2) Add a comment with the mentioned user, and then remove mention (via "Edit" action);
3) Do users have the ability to remove comments? If so, what happens if they add a comment with mentioned user and then remove this comment after some time?

4) Also, what happens when I'm looking at someone's page? Will I see ".. has mentioned **you** on ..."

2020-09-30 13:12 UTC, nvelychenko commented
> @nvelychenko,
> I'm just curious to know how it'll work in the following cases:
> 
> 1. Mention user in the existing comment (via "Edit" action) - will the event trigger;
> 2. Add a comment with the mentioned user, and then remove mention (via "Edit" action);
> 3. Do users have the ability to remove comments? If so, what happens if they add a comment with mentioned user and then remove this comment after some time?
> 4. Also, what happens when I'm looking at someone else's page? Will I see ".. has mentioned **you** on ..." in that case?

1. Nope, there is another event during entity updating.
2. Nothing will happen. See 1 point.
3. We have logic to remove all orphaned message entities, when a comment, node, or user entity is deleted.
4. Fixed to show **you** for the current user page, and **mentioned user** for other profiles.

2020-10-07 12:49 UTC, db-Matroskeen requested changes

2020-10-07 12:49 UTC, db-Matroskeen commented on themes/openideal_theme/openideal_theme.theme
> +    $partials = $elements['#message']->getText(\Drupal::languageManager()->getCurrentLanguage()->getId());
`getText()` accepts one more argument - delta. Can we pass "3" to get correct text line?

2020-10-07 12:49 UTC, db-Matroskeen commented on themes/openideal_theme/openideal_theme.theme
> +    $variables['#cache']['contexts'][] = 'user.is_user_profile_page';
We have to merge cache metadata (not overwrite). See `Drupal\Core\Cache\Cache.php` for helper methods.

2020-10-07 12:49 UTC, db-Matroskeen commented on themes/openideal_theme/openideal_theme.theme
> +    $elements = &$variables['elements'];
It seems ampersand is not necessary here.

2020-10-08 13:56 UTC, merged